### PR TITLE
Unifies upload for ext.commands and new implementation

### PR DESCRIPTION
**Pull request by Chiggy-Playz**
## Summary

Unifies upload for ext.commands and new implementation

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by GnomedDev — APPROVED** [review]
LGTM, if a bit jank

**Comment by Chiggy-Playz** [comment]
Oh and this also removes the need to call upload_guild_commands in setup. Its automatic now.

**Comment by AstreaTSS** [comment]
From personal experience: this does the job for guild commands, but a similar patch is needed for global commands. Honestly, it's not hard at all to do so, but still.

**Comment by Chiggy-Playz** [comment]
> From personal experience: this does the job for guild commands, but a similar patch is needed for global commands. Honestly, it's not hard at all to do so, but still.

Ah you're right I missed that. I'll fix it soon

**Comment by Chiggy-Playz** [comment]
@Astrea49 I have added global commands upload too and tested it too.

**Review by IAmTomahawkx — COMMENTED** [review]
im going to wait on this one to see about the upload system talked about in the discord server

**Pull request closed without merging**
